### ISSUE TITLE
Show chapter name when hovering the seekbar

### ISSUE THREAD

**Issue by 1Naim** [Zren/mpv-osc-tethys#1]
as the title, show chapter name when hovering the seekbar, just like the default osc

![image](http://midi.moe/f/tqked.png)

**Comment by Zren** [comment]
Hmm, I'd definitely be up for showing the chapter in a tooltip above the prev/next chapter buttons.

As for the seekbar, would it be okay to only show them as a tooltip over the "chapter tickmarks" if I turn them into buttons?

If not, then I guess I can make it a "subtitle" above or below the timestamp tooltip.

**Comment by lyturn** [comment]
Whether thumbnails can be displayed on the timeline.

**Comment by Zren** [comment]
I've a work in progress thumbnail support with the chapter title underneath which looks like YouTube.

https://github.com/Zren/mpv-osc-tethys/blob/thumb/osc_tethys.lua

![Screenshot_20220406_013050](https://user-images.githubusercontent.com/416367/161902901-452ffe57-27c9-4721-a9c8-17f023312334.png)

Once I've polished the Thumbnail generation (based on mpv_thumbnail_script) to always work (currently assumes linux + ffmpeg), I'll merge it.

**Comment by lyturn** [comment]
You're  good  job. but  I have a question, how do I set it up.
![014](https://user-images.githubusercontent.com/91406367/162392885-fc7ca34f-d09b-4e27-b49c-61fed83e4581.png)

**Comment by lyturn** [comment]
You're  good  job. but  I have a question, how do I set it up.
![014](https://user-images.githubusercontent.com/91406367/162392885-fc7ca34f-d09b-4e27-b49c-61fed83e4581.png)

**Comment by Zren** [comment]
I assume you're on Windows? I forgot to add the Windows "create directory" command, so it was failing to create `%TEMP%\mpv_thethys\`, which meant that it would error when trying to generate `%TEMP%\mpv_thethys\thumb.bgra`.

**Comment by lyturn** [comment]
On windows, the image still doesn't show. the cache folder "mpv_tethys" is empty.

**Comment by Zren** [comment]
Ah, I just noticed the thumb path is `C:\Users\Admin\AppData\Local\Temp\mpv_tethys/thumb.bgra`. Maybe that's it? It's weird that my Win7 VM works fine though.

I've added a bunch of mpv_thumbnail_script's error handling. Press the \`/~ key to open the console and view the logs.

**Comment by lyturn** [comment]
I still don't work here.
![012](https://user-images.githubusercontent.com/91406367/162605550-82745a49-6be1-4fea-9767-057e96a664a9.png)
![013](https://user-images.githubusercontent.com/91406367/162605572-5e2e733a-bea8-4f64-9e21-b465cc360572.png)

**Comment by lyturn** [comment]
"mpv.exe" version can display thumbnails normally
However, the "mpvnet.exe" version cannot display thumbnails properly.

**Comment by Zren** [comment]
@lyturn Thanks for the update!

Does changing `preferMpv = true,` to `preferMpv = false,` here work in MPV.net? https://github.com/Zren/mpv-osc-tethys/blob/thumb/osc_tethys.lua#L341

Does removing `osc_tethys.lua` and adding `mpv_thumbnail_script.lua` work in MPV.net?

**Comment by lyturn** [comment]
Now it works Change preferMpv "true" to "false" , you are awesome.

**Comment by Zren** [comment]
... Of course. That makes sense, because the executable is `mpvnet.exe` not `mpv.exe`.

https://github.com/Zren/mpv-osc-tethys/blob/thumb/osc_tethys.lua#L737-L740

Looks like to get `preferMpv = true` working, I'd need to change
```
    local mpvCommand = {
        "mpv",
        "--msg-level=all=error",
        "--hwdec=no",
...
```

to

```
    local mpvCommand = {
        "mpvnet",
        "--msg-level=all=error",
        "--hwdec=no",
...
```

It seems I'll need to copy `mpv_thumbnail_script`'s ExectuableFinder code to check if `mpv` exists, and if not, fallback to `mpvnet`. It's odd that `mpv_thumbnail_script` only checks if `ffmpeg` exists though.

**Comment by Zren** [comment]
Glad you got it working! Once I've finished the mpv/mpvnet check, I'll merge this into master.

**Comment by lyturn** [comment]
I found that changing preferMpv=true to preferMpvnet=true also works.

**Comment by Zren** [comment]
Chapter thumbnails in now merged into master along with the thumbnails.
