### ISSUE TITLE
Enable Title directly above the seek bar -Request

### ISSUE THREAD

**Issue by Cananbolt** [Zren/mpv-osc-tethys#16]
Fantastic OSC, thanks for sharing it. One question though, would it be possible to have the Title of the media directly above the seek bar (like https://github.com/cyl0/MordenX). The title on the border interferes with the way I set up mpv (OSD-Bar on the top and so on).

**Comment by Zren** [comment]
That would interfere with the Seekbar's tooltip + Thumbnail. I'd be fine with a toggle to hide the title alltogether, but you can already do this in `~/.config/mpv/script-opts/ocs.conf`:

https://github.com/Zren/mpv-osc-tethys#oscconf

```ini
title= 
``` 
Make sure there's a space after the `=`. If there's no space, the title will default to `mpv`.

**Comment by Cananbolt** [comment]
I now understand that the title in ModernX would not work as it will interfere with the seekbar's tooltip + Thumbnail. But how about something like mpv bottombar.

![20220606_195650](https://user-images.githubusercontent.com/100978782/172268050-717882d3-f168-44df-b0f3-6fe124d43d93.jpg)

I included a pic that shows the title of the video as such. Would that still be intrusive to the seekbar's tooltip + Thumbnail?

**Comment by Zren** [comment]
Are you asking for a row dedicated to the title under the seekbar? Not really interested in that.

**Comment by Cananbolt** [comment]
Yea, that wouldn't look good at all. I actually just played around with the script so that the border title size would be smaller, and now it's pretty much exactly how I want it. Thanks again for the script it's great.

P.S Is there any way you could show the audio track. The subtitle track selection is already there, and I would definitely love to see an audio track. Here's a pic of what I mean 

![image](https://user-images.githubusercontent.com/100978782/172471071-a4610f13-858b-42ce-b20d-feda6b2c5a1b.png)

Would it be possible to include the audio track on the left side of the subtitle track, as shown in the pic?

I'm definitely aware that this will take a lot of time as you would also have to create the tooltip code as well, but at the very least, I wanted to bring it to your attention. Sorry for all these requests.

**Comment by Zren** [comment]
It's there, just not visible unless there's more than 1 track. `Ctrl+F` for `cy_audio`.

```lua
    ne = new_element("cy_audio", "button")

    ne.visible = (#tracks_osc.audio > 1)
    ne.enabled = (#tracks_osc.audio > 0)
```

**Comment by Cananbolt** [comment]
This is exactly what I wanted, I changed the number 1 to 0, and now it shows the audio track all the time. Thank you so much.
