### ISSUE TITLE
`idlescreen` option to disable the logo

### ISSUE THREAD

**Issue by stax76** [Zren/mpv-osc-tethys#17]
I would like to request an option [idlescreen](https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua#L14) that allows to disable the logo and the logo drag and drop text.

In mpv.net there is an option [show-logo](https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#--show-logoyesno).

Users then have a choice if they want the mpv.net logo, the osc logo, or no logo.

It not only fixes the mpv.net logo overlap issue, but also overlap issues with many menu scripts:

https://github.com/CogentRedTester/mpv-file-browser

https://github.com/stax76/mpv-scripts/blob/main/osm.lua

Also, various bookmark and recent file menu scripts.

More info:

https://github.com/CogentRedTester/mpv-file-browser/issues/55

https://github.com/mpv-player/mpv/issues/10201

**Comment by Zren** [comment]
Hmm, there was also another been another bugfix commit from 21 days ago I need to merge too.

https://github.com/mpv-player/mpv/commits/master/player/lua/osc.lua
