### ISSUE TITLE
Show Chapter List on Key Bind

### ISSUE THREAD

**Issue by Cananbolt** [Zren/mpv-osc-tethys#19]
Currently, from what I am experiencing, I can only activate the Chapter List OSC when clicking the next and prev keys with my mouse on the Tethys layout. Is there any way to add or change a key bind that will let you see the chapter list with your custom key bind? 

For example, say in input.conf I put down "KEYBIND add chapter 1," can it then show the Chapter List on this script.

**Comment by Zren** [comment]
Find a way to trigger `osc-chapterlist`

https://github.com/Zren/mpv-osc-tethys/blob/master/osc_tethys.lua#L5228-L5230

```lua
mp.register_script_message("osc-chapterlist", function(dur)
    show_message(get_chapterlist(), dur)
end)
```

**Comment by Zren** [comment]
Simple google for `osc-chapterlist` comes up with:

```
KEYBIND script-message osc-chapterlist
```

**Comment by Cananbolt** [comment]
Thanks a bunch I did...

KEYBIND add chapter 1 ; script-message osc-chapterlist

...and it works great. The only problem is that I would like to change the position of the chapter list without affecting my mpv.conf file. Any ideas

**Comment by Zren** [comment]
show_message() and render_message() are here:

https://github.com/Zren/mpv-osc-tethys/blob/master/osc_tethys.lua#L2910-L2959

You could add `\\pos(0,0)` to that `"{\\bord" .. outline .. "\\fs" .. fontsize .. "}"` to move the message around I think.

**Comment by Cananbolt** [comment]
Got it thanks for your help.
