### ISSUE TITLE
Thumbnail not appearing

### ISSUE THREAD

**Issue by the-nos4a2** [Zren/mpv-osc-tethys#2]
![image](https://user-images.githubusercontent.com/66081804/167655316-8bcd39e1-70fc-41cc-9bf5-92624db73f08.png)

**Comment by Zren** [comment]
Looks like there's a cache, so it's detected as a remote file. The script doesn't display thumbnails when it detects remote urls.

https://github.com/Zren/mpv-osc-tethys/blame/master/osc_tethys.lua#L435

Is it a `http://` or `https://` url, or something else?

**Comment by the-nos4a2** [comment]
In this case it was, but even in local files it doesn't show

**Comment by the-nos4a2** [comment]
Ok, it's working now, I don't know why it wasn't working, thank you very much!
