### ISSUE TITLE
Request: Slice longfilenames on Title

### ISSUE THREAD

**Issue by Cananbolt** [Zren/mpv-osc-tethys#23]
I know we can reduce the font size of the Title, but I think it'll also be helpful to slice files with long names on the title.

**Comment by Zren** [comment]
Are you referring to the title when the titlebar is hidden (`borders=no`)?

![2022-10-12___18-00-30](https://user-images.githubusercontent.com/416367/195456053-1af3551a-848f-4e33-9080-36b056013961.png)

It should wrap, but it seems like it's wrapping at the right edge of the window and not at the left edge of the window close buttons. There's enough room for 2 lines of text I think.

**Comment by Cananbolt** [comment]
Yes I am referring to this. Instead of it getting it to wrap, is it possible just to slice up to a certain amount of letters.

For example: say if I want to slice starting from the 30th letter.

After the 30th letter it will cut out rest of the title and replace it with {3 dots} ...

**Comment by Zren** [comment]
Hmm. It's not really possible to do text ellision with overflow. I'm already using `\crop(x1, y1, x2, y2)`, however the text is wrapping when it hits the edge of the screen. I could probably find a way to set the width of the text, but I might as well use `\q2` to set no text wrapping.

https://aegi.vmoe.info/docs/3.0/ASS_Tags/#index26h3

**Comment by Cananbolt** [comment]
This is actually what I wanted. I didn't want it to make a 2nd line. Thanks as always
