### ISSUE TITLE
Lag when using tumbnails

### ISSUE THREAD

**Issue by the-nos4a2** [Zren/mpv-osc-tethys#3]
Hello, I have a problem.
When watching anything on mpv the tumbnails from osc tethys lag all the interface and even make it freeze.

Could you help me?

Thanks

**Comment by Zren** [comment]
Atm, the thumbnail generation is blocking. I added a debounce delay to generate the thumbnail if you stop moving the mouse for 200ms, but it's not working very well.

I was hoping to keep this as a single script to make it easier to install, but it seems there's a reason that https://github.com/TheAMM/mpv_thumbnail_script/releases is two different lua scripts.

I've tested a quick refactor using `mpv_thumbnail_script_server.lua` and it seems to work well. I've just gotta polish it and remove my old thumbnail code before releasing it.

**Comment by Zren** [comment]
Try the https://github.com/Zren/mpv-osc-tethys/tree/thumbserver branch:

* https://raw.githubusercontent.com/Zren/mpv-osc-tethys/thumbserver/osc_tethys.lua
* https://raw.githubusercontent.com/Zren/mpv-osc-tethys/thumbserver/mpv_thumbnail_script_server.lua

**Comment by the-nos4a2** [comment]
Thank you!

**Comment by the-nos4a2** [comment]
And how can I make the tumbnails work on remote files?

**Comment by Zren** [comment]
https://github.com/Zren/mpv-osc-tethys#mpv_thumbnail_scriptconf

```
# Allow thumbnailing network paths (naive check for "://")
thumbnail_network=yes
```
