### ISSUE TITLE
Missing audio track button

### ISSUE THREAD

**Issue by da3dsoul1** [Zren/mpv-osc-tethys#31]
Dude, first of all, thank you very much for the theme,  it's what I wanted for so long, but couldn't do because of poor skills and laziness.

So the issue is tethys theme is missing audio track button as stated above, example: 
![image](https://user-images.githubusercontent.com/111184581/217080067-a46e631b-1f35-4a29-be1b-dd4c1ce5ff08.png)

And the default OSC:
![image](https://user-images.githubusercontent.com/111184581/217080880-3e34eb8f-e1f1-4199-ba79-8e3138226177.png)

Is there any way to add it, if so how can I do it? Thank you very much in advance!

**Comment by Zren** [comment]
It should appear automatically when there's `>= 2` audio tracks.

https://github.com/Zren/mpv-osc-tethys/blob/master/osc_tethys.lua#L4436

**Comment by da3dsoul1** [comment]
Indeed, didn't try it on multiple audio tracks the first time, thanks!
