### ISSUE TITLE
Does not longer work with mpv 0.38.

### ISSUE THREAD

**Issue by houssemko** [Zren/mpv-osc-tethys#37]
No OSC anymore

**Comment by mdouchement** [comment]
There are some API changes:
- MPV changelogs: https://github.com/mpv-player/mpv/blob/v0.38.0/DOCS/interface-changes.rst
- Helpful working example: https://github.com/mpv-player/mpv/blob/v0.38.0/player/lua/osc.lua

I fixed a modified version of this OSC Lua file in my own repo: https://github.com/mdouchement/mpv/pull/1/files#diff-b1ca08232fb1c9936934acd30ec0139883a45d0db69237bba10154f1d9481bbd

Applying the same changes in this repo will fix the issue.

> Launching mpv from a terminal helps to spot all the issues from any lua scripts or configuration.
